id: A976660B8
title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying (Sojong)
  the Three Sets of Vows'
type: translation
pechas:
- I5568D549
- ID2B27DF2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:10.240969
  last_modified_at: 2023-01-04 11:50:10.240983
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5568D549/3CDF: B274
  ID2B27DF2/B493: B274
